### ISSUE TITLE
Question about input to dismay

### ISSUE THREAD

**Issue by kvittingseerup** [skinnider/dismay#1]
Thanks for the nice package! 

Is there any input type prefrence? raw counts? CPM? TPM?

(and what did you use in the recent nature methods paper?)

Cheers
Kristoffer

**Comment by skinnider** [comment]
Hi Kristoffer, dismay is flexible about what kind of input it takes. If you provide a NxM matrix it will return a MxM matrix - so genes in columns will give you a gene-by-gene matrix, cells in columns a cell-by-cell matrix. In the paper, we used the datasets as the authors had provided them; you can find these datasets at https://github.com/skinnider/SCT-MoA. The only thing I would say is the measures that look at binary presence/absence (Hamming, Dice, Jaccard) as well as measures that specifically take zeroes into account (zero-inflated Kendall correlation) would depend on the presence of zeroes in the dataset, and so for example, normalization methods like [sctransform](https://www.biorxiv.org/content/biorxiv/early/2019/03/18/576827.full.pdf) which produce dense matrices would not be compatible with these.

**Comment by kvittingseerup** [comment]
Thanks for the clarification :-)
